USE [master]
GO

/****** Object:  Database [IQBusiness]    Script Date: 2019/04/23 03:27:44 ******/
CREATE DATABASE [IQBusiness]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IQBusiness', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\IQBusiness.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IQBusiness_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\IQBusiness_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [IQBusiness] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IQBusiness].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IQBusiness] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IQBusiness] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IQBusiness] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IQBusiness] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IQBusiness] SET ARITHABORT OFF 
GO

ALTER DATABASE [IQBusiness] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IQBusiness] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IQBusiness] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IQBusiness] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IQBusiness] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IQBusiness] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IQBusiness] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IQBusiness] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IQBusiness] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IQBusiness] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IQBusiness] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IQBusiness] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IQBusiness] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IQBusiness] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IQBusiness] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IQBusiness] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IQBusiness] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IQBusiness] SET RECOVERY FULL 
GO

ALTER DATABASE [IQBusiness] SET  MULTI_USER 
GO

ALTER DATABASE [IQBusiness] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IQBusiness] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IQBusiness] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IQBusiness] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IQBusiness] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IQBusiness] SET QUERY_STORE = OFF
GO

USE [IQBusiness]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [IQBusiness] SET  READ_WRITE 
GO


